n_module: 5
n_feature: 512
n_output: 1
num_epochs: 750
learning_rate: 0.001
batch_size: 32
valid_batch_size: 256
log_file_name: training.log
normalize: True
scheduler: ReduceLROnPlateau[factor=0.5,patience=30,eps=5e-8]
folder_suffix: H_concat_emb
target_names: 
- atom_y
mask_atom: True
stop_low_lr: True
ext_atom_features: raw_qmd_features
ext_atom_features_norm: by_element
ext_atom_dim: 3
ext_atom_method: emb