new_test_dir_prefix: nmrshiftdb2_emb_H
folder_name: # note that folder_name should be a list for test.py to decide which test process to choose. These 5 models together provide the ensemble prediction.
  - model/H_concat_emb1
  - model/H_concat_emb2
  - model/H_concat_emb3
  - model/H_concat_emb4
  - model/H_concat_emb5
dataset_args: 
  root: data/NMRShiftDB2_DFT/hydrogen/
split: data/NMRShiftDB2_DFT/hydrogen/processed/split.pt
dataset_class: NMRDatasetFromProcessed
labeled_data: True
ignore_val: True 
avg_iso_atoms: False
