test_dir_prefix: case_study_test
folder_name_list: 
  - 240227_205751C_concat_emb
  - 240227_205751C_concat_emb
dataset_args: 
  root: data/nmr_case_study_data/
split: data/nmr_case_study_data/processed/split.pt
all_test: 7  # a temp config to provide the number of mols in dataset for all test
labeled_data: False
save_csv: True
ignore_val: True 